// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARNCjXZAF_WjPgP4TzaW1DhEo69Zs-aQk',
    appId: '1:56402290904:web:28504f85c1cd7ddc8c0fad',
    messagingSenderId: '56402290904',
    projectId: 'blackdog-dev-6104f',
    authDomain: 'blackdog-dev-6104f.firebaseapp.com',
    storageBucket: 'blackdog-dev-6104f.firebasestorage.app',
    measurementId: 'G-L0NYXD7WLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82lksoj6AlzInS0H-Zm9h45cE9hdnAOA',
    appId: '1:56402290904:android:aed4c5ade249bb0c8c0fad',
    messagingSenderId: '56402290904',
    projectId: 'blackdog-dev-6104f',
    storageBucket: 'blackdog-dev-6104f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJHHUTYz3Hx8dG6B--v6m8Vycc4wNCP4',
    appId: '1:56402290904:ios:0a0a87865615488e8c0fad',
    messagingSenderId: '56402290904',
    projectId: 'blackdog-dev-6104f',
    storageBucket: 'blackdog-dev-6104f.firebasestorage.app',
    iosClientId: '56402290904-gj3npej1b4234avk49dutrdv1au51ao5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dog1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJHHUTYz3Hx8dG6B--v6m8Vycc4wNCP4',
    appId: '1:56402290904:ios:0a0a87865615488e8c0fad',
    messagingSenderId: '56402290904',
    projectId: 'blackdog-dev-6104f',
    storageBucket: 'blackdog-dev-6104f.firebasestorage.app',
    iosClientId: '56402290904-gj3npej1b4234avk49dutrdv1au51ao5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dog1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARNCjXZAF_WjPgP4TzaW1DhEo69Zs-aQk',
    appId: '1:56402290904:web:b65f9cb144837f388c0fad',
    messagingSenderId: '56402290904',
    projectId: 'blackdog-dev-6104f',
    authDomain: 'blackdog-dev-6104f.firebaseapp.com',
    storageBucket: 'blackdog-dev-6104f.firebasestorage.app',
    measurementId: 'G-CBT1TSRRVX',
  );
}
